services:
  jenkins:
    image: docker.io/jenkins/jenkins:alpine-jdk21
    restart: unless-stopped
    security_opt:
      - label=type:container_runtime_t
    volumes:
      - hb_jenkins_home:/var/jenkins_home:z
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z
    networks:
      - hb-devops-network
    ports:
      - '8880:8080'

  # gitlab:
  #   image: docker.io/gitlab/gitlab-ce:latest
  #   restart: unless-stopped
  #   shm_size: 256m
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 4g
  #   volumes:
  #     - hb_gitlab_data:/var/opt/gitlab:z
  #     - hb_gitlab_config:/etc/gitlab:z
  #     - hb_gitlab_logs:/var/log/gitlab:z
  #   networks:
  #     - hb-devops-network
  #   ports:
  #     - '8080:80'
  #     - '8443:443'
  #     - '8022:22'
  #   environment:
  #     GITLAB_ROOT_EMAIL: 'admin@hireben.dev'
  #     GITLAB_ROOT_PASSWORD: 'P@ssw0rd'
  #     GITLAB_OMNIBUS_CONFIG: |
  #       external_url 'http://localhost:8080'

volumes:
  hb_jenkins_home:
  # hb_gitlab_data:
  # hb_gitlab_config:
  # hb_gitlab_logs:

networks:
  hb-devops-network: