services:
  # jenkins:
  #   image: docker.io/jenkins/jenkins:alpine-jdk21
  #   restart: unless-stopped
  #   security_opt:
  #     - label=type:container_runtime_t
  #   volumes:
  #     - hb_jenkins_home:/var/jenkins_home:z
  #     - /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z
  #   networks:
  #     - hb-devops-network
  #   ports:
  #     - '8880:8080'

  gitlab:
    image: docker.io/gitlab/gitlab-ce:latest
    restart: unless-stopped
    shm_size: 256m
    volumes:
      - hb_gitlab_data:/var/opt/gitlab:z
      - hb_gitlab_config:/etc/gitlab:z
      - hb_gitlab_logs:/var/log/gitlab:z
    networks:
      - hb-devops-network
    ports:
      - '8081:8081'
      - '8022:22'
    environment:
      GITLAB_ROOT_EMAIL: 'admin@hireben.dev'
      GITLAB_ROOT_PASSWORD: 'P@ssw0rd'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost:8081'
        gitlab_rails['gitlab_shell_ssh_port'] = 8022
        postgresql['shared_buffers'] = '64MB'
        redis['maxmemory'] = '32mb'
        puma['worker_processes'] = 2
        actioncable['worker_pool_size'] = 1
        alertmanager['enable'] = false
        sidekiq['enable'] = false
        gitlab_rails['enable_mailer'] = false
        gitlab_rails['enable_job_artifacts'] = false
        gitlab_rails['incoming_email_enabled'] = false
        gitlab_rails['backup_keep_time'] = 0
        mattermost['enable'] = false
        registry['enable'] = false
        gitlab_ci['gitlab_runner'] = false
        gitlab_exporter['enable'] = false
        gitlab_kas['enable'] = false
        letsencrypt['enable'] = false
        node_exporter['enable'] = false
        postgres_exporter['enable'] = false
        prometheus['enable'] = false
        redis_exporter['enable'] = false

volumes:
  # hb_jenkins_home:
  hb_gitlab_data:
  hb_gitlab_config:
  hb_gitlab_logs:

networks:
  hb-devops-network:
