services:
  jenkins:
    image: jenkins/jenkins:alpine-jdk21
    container_name: jenkins-controller
    restart: unless-stopped
    volumes:
      - hb_jenkins_home:/var/jenkins_home
      - /run/podman/podman.sock:/var/run/docker.sock:Z
    networks:
      - hb-devops-network
    ports:
      - "8880:8080"
    environment:
      GITLAB_HOST: gitlab:80

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab-server
    restart: unless-stopped
    shm_size: 256m
    volumes:
      - hb_gitlab_data:/var/opt/gitlab
      - hb_gitlab_config:/etc/gitlab
      - hb_gitlab_logs:/var/log/gitlab
    networks:
      - hb-devops-network
    ports:
      - "8080:80"
      - "8443:443"
      - "8022:22"
    environment:
      JENKINS_HOST: jenkins:8080

volumes:
  hb_jenkins_home:
  hb_gitlab_data:
  hb_gitlab_config:
  hb_gitlab_logs:

networks:
  hb-devops-network: